# Visualizing Area Summaries

* It can be difficult to easily summarize GEE imageCollections and images over an area in an interactive environment
* geeViz provides two complementary approaches for area charting:
  1. **Map-based charting** (`canAreaChart` in `Map.addLayer`) — interactive charts inside the geeView map UI
  2. **Inline charting** (`geeViz.chartingLib`) — Plotly charts rendered directly in a notebook cell
* This notebook demonstrates both approaches side-by-side for each example



Copyright 2026 Ian Housman

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

[![github](https://img.shields.io/badge/-see%20sources-white?logo=github&labelColor=555)](https://github.com/gee-community/geeviz/blob/master/examples/areaChart_examples.ipynb) 
[![github](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/gee-community/geeViz/blob/master/examples/areaChart_examples.ipynb)

In [2]:
#Import modules
try:
    import  geeViz.geeView as geeView
except:
    !python -m pip install geeViz
    import  geeViz.geeView as geeView

import geeViz.getImagesLib as gil
import geeViz.chartingLib as cl

Earth Engine not initialized. Current Earth Engine best practices recommend running: `ee.Authenticate()`,`ee.Initialize(project="someProjectID")`, before importing geeViz.
geeViz will try to authenticate (if needed) and initialize automatically now. If this fails, please run these commands manually.
Successfully initialized GEE
PyTables is not installed. No support for HDF output.

In [3]:
import pandas as pd
ee = geeView.ee
Map = geeView.Map
Map.clearMap()
print('done')

done

* There are many different formats of data geeViz's area charting module can handle
* The most common is charting the percent or area in hectares or acres of thematic classes of an image collection
* If an imageCollection has `class_values`, `class_names`, `class_palette` properties for its images, all charts will automatically be populated with those names and colors

* First, we will look at these properties for a couple available images and image collections

In [4]:
lcms = ee.ImageCollection("USFS/GTAC/LCMS/v2024-10")
nlcd = ee.ImageCollection("USGS/NLCD_RELEASES/2021_REL/NLCD").select(['landcover'])
def get_props_dataFrames(props,bandNames = None):
    props = {k:i for k,i in props.items() if k.find('_class_')>-1}

    if bandNames == None:
        bandNames = list(set([k.split('_class_')[0] for k in props.keys()]))
    out = {}
    for bn in bandNames:
        print(bn)
        df = pd.DataFrame({'Values':props[f'{bn}_class_values'],
                           'Names':props[f'{bn}_class_names'],
                           'Colors':props[f'{bn}_class_palette']})
        display(df)
        out[bn]=df
    # return out
lcms_props = lcms.first().toDictionary().getInfo()
nlcd_props = nlcd.first().toDictionary().getInfo()


lcms_thematic_bandNames = lcms.select(['Change','Land_Cover','Land_Use']).first().bandNames().getInfo()

nlcd_landcover_bandNames = ['landcover']

get_props_dataFrames(lcms_props,lcms_thematic_bandNames)
get_props_dataFrames(nlcd_props,nlcd_landcover_bandNames)


# Shorten NLCD class names for later use
nlcd_class_names_key = f'{nlcd_landcover_bandNames[0]}_class_names'
nlcd_class_names_shortened = [nm.split(':')[0] for nm in nlcd_props[nlcd_class_names_key]]
nlcd_props_shortened_names = nlcd_props
nlcd_props_shortened_names[nlcd_class_names_key] = nlcd_class_names_shortened

print('Shortened NLCD class names:')
get_props_dataFrames(nlcd_props_shortened_names,nlcd_landcover_bandNames)

Change

    Values                               Names  Colors
0        1                                Wind  ff09f3
1        2                           Hurricane  541aff
2        3              Snow or Ice Transition  e4f5fd
3        4                         Desiccation  cc982e
4        5                          Inundation  0adaff
5        6                     Prescribed Fire  a10018
6        7                            Wildfire  d54309
7        8      Mechanical Land Transformation  fafa4b
8        9                        Tree Removal  afde1c
9       10                         Defoliation  ffc80d
10      11                Southern Pine Beetle  a64c28
11      12  Insect, Disease, or Drought Stress  f39268
12      13                          Other Loss  c291d5
13      14      Vegetation Successional Growth  00a398
14      15                              Stable  3d4551
15      16            Non-Processing Area Mask  1b1716

Land_Cover

    Values                              Names  Colors
0        1                              Trees  004e2b
1        2  Tall Shrubs & Trees Mix (AK Only)  009344
2        3                 Shrubs & Trees Mix  61bb46
3        4        Grass/Forb/Herb & Trees Mix  acbb67
4        5                 Barren & Trees Mix  8b8560
5        6              Tall Shrubs (AK Only)  cafd4b
6        7                             Shrubs  f89a1c
7        8       Grass/Forb/Herb & Shrubs Mix  8fa55f
8        9                Barren & Shrubs Mix  bebb8e
9       10                    Grass/Forb/Herb  e5e98a
10      11       Barren & Grass/Forb/Herb Mix  ddb925
11      12               Barren or Impervious  893f54
12      13                        Snow or Ice  e4f5fd
13      14                              Water  00b6f0
14      15           Non-Processing Area Mask  1b1716

Land_Use

   Values                     Names  Colors
0       1               Agriculture  fbff97
1       2                 Developed  e6558b
2       3                    Forest  004e2b
3       4                     Other  9dbac5
4       5      Rangeland or Pasture  a6976a
5       6  Non-Processing Area Mask  1b1716

landcover

    Values                                              Names  Colors
0       11  Open water: areas of open water, generally wit...  466b9f
1       12  Perennial ice/snow: areas characterized by a p...  d1def8
2       21  Developed, open space: areas with a mixture of...  dec5c5
3       22  Developed, low intensity: areas with a mixture...  d99282
4       23  Developed, medium intensity: areas with a mixt...  eb0000
5       24  Developed high intensity: highly developed are...  ab0000
6       31  Barren land (rock/sand/clay): areas of bedrock...  b3ac9f
7       41  Deciduous forest: areas dominated by trees gen...  68ab5f
8       42  Evergreen forest: areas dominated by trees gen...  1c5f2c
9       43  Mixed forest: areas dominated by trees general...  b5c58f
10      52  Shrub/scrub: areas dominated by shrubs less th...  ccb879
11      71  Grassland/herbaceous: areas dominated by grama...  dfdfc2
12      81  Pasture/hay: areas of grasses, legumes, or gra...  dcd939
13      82  Cultivated crops: areas used for the productio...  ab6c28
14      90  Woody wetlands: areas where forest or shrublan...  b8d9eb
15      95  Emergent herbaceous wetlands: areas where pere...  6c9fb8

Shortened NLCD class names:
landcover

    Values                         Names  Colors
0       11                    Open water  466b9f
1       12            Perennial ice/snow  d1def8
2       21         Developed, open space  dec5c5
3       22      Developed, low intensity  d99282
4       23   Developed, medium intensity  eb0000
5       24      Developed high intensity  ab0000
6       31  Barren land (rock/sand/clay)  b3ac9f
7       41              Deciduous forest  68ab5f
8       42              Evergreen forest  1c5f2c
9       43                  Mixed forest  b5c58f
10      52                   Shrub/scrub  ccb879
11      71          Grassland/herbaceous  dfdfc2
12      81                   Pasture/hay  dcd939
13      82              Cultivated crops  ab6c28
14      90                Woody wetlands  b8d9eb
15      95  Emergent herbaceous wetlands  6c9fb8

## Define a Study Area for Inline Charts

* The map-based charting uses the current map extent (or a selected feature) as the summary area
* For the inline `chartingLib` examples we need to define an explicit geometry
* This study area is reused throughout the notebook

In [5]:
# Study area: a rectangle in the western US (Colorado front range area)
study_area = ee.Geometry.Polygon(
    [[[-106.0, 39.5], [-105.0, 39.5], [-105.0, 40.5], [-106.0, 40.5], [-106.0, 39.5]]]
)
print('Study area defined')

Study area defined

---
## Basic Area Charting

* This example will show the most basic method for adding area chart layers

* By setting `"canAreaChart":True`, the layer will be added to area charting. Available properties (shown above) will be used to set up names and colors

* There are many options for area charting. Most of these options are provided as a dictionary using the `areaChartParams` key. This example shows two different `chartType`s 

* Using the `Map.turnOnAutoAreaCharting()` method will turn on autmatic area charting. This will use the map extent as the summary area.

* Additional methods are `Map.turnOnSelectionAreaCharting()` and `Map.turnOnUserDefinedAreaCharting()` for turning on different methods of providing areas to summarize. You can also change the method being used in the geeView UI under `Tools -> Area Tools`

In [6]:
# Map-based approach
Map.clearMap()


Map.addLayer(lcms.select(['Land_Cover']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'chartType':'stacked-line'}},'LCMS Land Cover')
Map.addLayer(nlcd.select(['landcover']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'chartType':'stacked-bar'}},'NLCD Land Cover')



Map.turnOnAutoAreaCharting()
Map.view()

Adding layer: LCMS Land Cover
Adding layer: NLCD Land Cover
Starting webmap
Using default refresh token for geeView
Local web server at: http://localhost:8001/geeView/ already serving.
cwd c:\RCR\geeVizBuilder\geeViz\examples
geeView URL: http://localhost:8001/geeView/?projectID=rcr-gee-training&accessToken=REDACTED&accessTokenCreationTime=1772823552945

### Inline chartingLib equivalent

* `cl.summarize_and_chart` auto-detects thematic data and uses `frequencyHistogram`
* Returns both a `pandas.DataFrame` and a `plotly.graph_objects.Figure`
* Use `chart_type='bar'` and `stacked=True` for a stacked bar chart

In [7]:
# Inline: Stacked time series of LCMS Land Cover
df, fig = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    title='LCMS Land Cover',
    stacked=True,
)
fig.show()
display(df)

,Trees,Grass/Forb/Herb,Barren & Grass/Forb/Herb Mix,Barren or Impervious,Snow or Ice,Water,Non-Processing Area Mask,Shrubs & Trees Mix,Grass/Forb/Herb & Trees Mix,Barren & Trees Mix,Shrubs,Grass/Forb/Herb & Shrubs Mix,Barren & Shrubs Mix
1985,56.94,17.17,0.01,6.58,0.07,1.43,4.21,0.82,4.84,0.54,3.44,3.74,0.21
1986,59.05,15.96,0.01,8.20,0.07,1.46,0.90,0.89,5.00,0.61,2.88,4.73,0.24
1987,59.47,15.84,0.01,8.34,0.05,1.45,0.08,0.95,5.22,0.66,2.69,4.99,0.27
1988,59.83,15.60,0.01,8.08,0.05,1.44,0.03,0.96,5.27,0.64,2.63,5.20,0.26
1989,60.27,15.30,0.01,7.98,0.04,1.41,0.01,0.94,5.29,0.64,2.62,5.23,0.26
1990,60.63,15.17,0.01,7.86,0.04,1.42,0.01,0.93,5.32,0.62,2.59,5.16,0.25
1991,60.77,15.26,0.01,7.69,0.04,1.43,0.01,0.94,5.31,0.61,2.58,5.11,0.24
1992,60.90,15.08,0.01,7.71,0.04,1.43,0.01,0.94,5.42,0.61,2.54,5.06,0.25
1993,61.15,14.77,0.01,7.83,0.04,1.45,0.00,0.91,5.30,0.62,2.44,5.24,0.25
1994,61.13,14.84,0.01,7.76,0.04,1.47,0.00,0.94,5.48,0.60,2.39,5.10,0.24
1995,61.61,14.49,0.01,7.89,0.04,1.48,0.00,0.93,5.25,0.61,2.00,5.45,0.24
1996,61.63,14.32,0.01,8.01,0.04,1.50,0.00,0.92,5.29,0.61,1.92,5.49,0.25
1997,61.64,14.28,0.01,7.99,0.04,1.51,0.00,0.93,5.38,0.60,1.93,5.44,0.25
1998,61.67,13.95,0.01,8.12,0.04,1.51,0.00,0.90,5.27,0.62,1.94,5.71,0.27
1999,61.49,13.95,0.01,8.13,0.04,1.52,0.00,0.94,5.42,0.62,1.93,5.69,0.26
2000,60.89,13.78,0.01,8.39,0.03,1.49,0.00,0.90,5.39,0.65,1.96,6.25,0.26
2001,60.74,13.63,0.01,8.46,0.03,1.47,0.00,0.93,5.48,0.65,1.99,6.33,0.27
2002,60.54,13.56,0.01,8.55,0.03,1.42,0.00,0.93,5.60,0.64,2.02,6.43,0.27
2003,60.66,13.54,0.01,8.57,0.03,1.45,0.00,0.95,5.52,0.65,2.01,6.31,0.28
2004,60.66,13.36,0.01,8.68,0.03,1.46,0.00,0.98,5.59,0.65,2.02,6.28,0.29
2005,60.78,13.38,0.01,8.57,0.03,1.49,0.00,0.97,5.54,0.66,2.02,6.26,0.29
2006,60.34,13.45,0.01,8.57,0.03,1.47,0.00,0.98,5.74,0.67,2.09,6.36,0.29
2007,60.44,13.38,0.01,8.58,0.03,1.49,0.00,0.98,5.80,0.67,2.08,6.23,0.30
2008,60.27,13.32,0.01,8.57,0.03,1.51,0.00,1.01,5.89,0.67,2.09,6.33,0.30
2009,60.33,13.29,0.01,8.56,0.03,1.54,0.00,1.05,5.90,0.67,2.08,6.23,0.31
2010,60.18,13.35,0.01,8.50,0.03,1.55,0.00,1.05,6.09,0.68,2.12,6.14,0.31
2011,60.00,13.42,0.01,8.46,0.03,1.55,0.00,1.06,6.16,0.67,2.11,6.22,0.30
2012,59.87,13.52,0.01,8.41,0.03,1.51,0.00,1.06,6.27,0.67,2.12,6.21,0.30
2013,59.59,13.75,0.01,8.44,0.03,1.52,0.00,1.13,6.40,0.67,2.14,6.01,0.31
2014,59.64,13.88,0.01,8.34,0.03,1.55,0.00,1.15,6.47,0.68,2.15,5.79,0.32
2015,59.52,13.83,0.01,8.53,0.03,1.56,0.00,1.14,6.46,0.77,2.18,5.65,0.33
2016,59.12,13.57,0.01,8.76,0.03,1.56,0.00,1.12,6.73,0.76,2.22,5.80,0.32
2017,59.01,13.40,0.01,8.99,0.02,1.57,0.00,1.09,6.66,0.75,2.28,5.89,0.33
2018,58.84,13.29,0.01,9.08,0.02,1.57,0.00,1.10,6.80,0.74,2.34,5.87,0.34
2019,58.83,13.21,0.01,9.20,0.03,1.57,0.00,1.14,6.89,0.71,2.35,5.72,0.35
2020,58.64,13.29,0.01,9.14,0.03,1.56,0.00,1.12,7.12,0.69,2.41,5.61,0.37
2021,57.01,13.41,0.01,10.43,0.02,1.57,0.00,1.11,7.49,0.69,2.53,5.37,0.37
2022,57.09,13.55,0.01,9.78,0.02,1.56,0.00,1.13,7.94,0.69,2.55,5.31,0.39
2023,57.44,13.47,0.01,9.16,0.02,1.59,0.00,1.17,8.45,0.68,2.45,5.16,0.39
2024,57.35,12.68,0.01,9.00,0.02,1.58,0.00,1.13,8.87,0.68,2.46,5.82,0.41

In [ ]:
# Inline: Stacked bar chart of NLCD Land Cover
df, fig = cl.summarize_and_chart(
    nlcd.select(['landcover']),
    study_area,
    title='NLCD Land Cover',
    chart_type='bar',
    stacked=True,
)
fig.show()
display(df)

---
## Line and Sankey Charts

* For thematic imageCollections, line and sankey charts are supported

* You can specify one or both within the `areaChartParams` dictionary. By default, line is chosen. (e.g. `"areaChartParams":{"sankey":True}`)

* Note that sankey charts work well at showing transitions between classes. Since the number of transition classes is the number of classes<sup>2</sup>, if there are many classes, sankey charting will be quite slow and may error out.

* For sankey charting, you can specify transition periods in the code using the `sankeyTransitionPeriods` key in `areaChartParams` (e.g. `"sankeyTransitionPeriods":[[1985,1987],[2000,2002],[2020,2022]]`), or leave it blank and geeViz will try to figure out a good set given the years of the provided imageCollection. Note that if you add imageCollections with different time extents, geeViz will take the intersection for the default years. You can add and change the periods in the geeView UI as well under `Tools -> Area Tools -> Area Tools Parameters`

In [8]:
# Map-based approach
Map.clearMap()

Map.addLayer(lcms.select(['Change']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'sankey':True}},'LCMS Change')

Map.addLayer(lcms.select(['Land_Cover']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'sankey':True}},'LCMS Land Cover')

Map.addLayer(lcms.select(['Land_Use']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'sankey':True}},'LCMS Land Use')


Map.turnOnAutoAreaCharting()
Map.view()

Adding layer: LCMS Change
Adding layer: LCMS Land Cover
Adding layer: LCMS Land Use
Starting webmap
Using default refresh token for geeView
Starting local web server at: http://localhost:8001/geeView/
HTTP server command: ['c:\\RCR\\geeVizBuilder\\venv\\Scripts\\python.exe', '-m', 'http.server', '8001']
Done
cwd c:\RCR\geeVizBuilder\geeViz\examples
geeView URL: http://localhost:8001/geeView/?projectID=rcr-gee-training&accessToken=REDACTED&accessTokenCreationTime=1772826363798

### Inline chartingLib equivalent

* Set `sankey=True` and provide `transition_periods` as a list of `[start_year, end_year]` pairs
* `min_percentage` filters out small flows for readability

In [9]:
# Inline: Sankey diagram of LCMS Change transitions
sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
    lcms.select(['Change']),
    study_area,
    sankey=True,
    transition_periods=[[1985, 1990], [2005, 2010], [2018, 2023]],
    title='LCMS Change Transitions',
    min_percentage=0.5,
)
sankey_fig.show()
print('Source-Target-Value table:')
display(sankey_df)
print('Transition matrix:')
display(matrix_df)

Source-Target-Value table:

,source,target,value,source_name,target_name,source_color,target_color,period
0,13,29,6.48,1985-1990 Vegetation Successional Growth,1985-1990 Vegetation Successional Growth,#00a398,#00a398,1985-1990 -> 1985-1990
1,14,30,93.11,1985-1990 Stable,1985-1990 Stable,#3d4551,#3d4551,1985-1990 -> 1985-1990
2,27,43,5.82,"2005-2010 Insect, Disease, or Drought Stress","2005-2010 Insect, Disease, or Drought Stress",#f39268,#f39268,2005-2010 -> 2005-2010
3,29,45,2.02,2005-2010 Vegetation Successional Growth,2005-2010 Vegetation Successional Growth,#00a398,#00a398,2005-2010 -> 2005-2010
4,30,46,92.10,2005-2010 Stable,2005-2010 Stable,#3d4551,#3d4551,2005-2010 -> 2005-2010

Transition matrix:

,Wind 1985-1990,Hurricane 1985-1990,Snow or Ice Transition 1985-1990,Desiccation 1985-1990,Inundation 1985-1990,Prescribed Fire 1985-1990,Wildfire 1985-1990,Mechanical Land Transformation 1985-1990,Tree Removal 1985-1990,Defoliation 1985-1990,...,Wildfire 2005-2010,Mechanical Land Transformation 2005-2010,Tree Removal 2005-2010,Defoliation 2005-2010,Southern Pine Beetle 2005-2010,"Insect, Disease, or Drought Stress 2005-2010",Other Loss 2005-2010,Vegetation Successional Growth 2005-2010,Stable 2005-2010,Non-Processing Area Mask 2005-2010
Wind 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Hurricane 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Snow or Ice Transition 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Desiccation 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Inundation 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Prescribed Fire 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wildfire 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mechanical Land Transformation 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tree Removal 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Defoliation 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Southern Pine Beetle 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"Insect, Disease, or Drought Stress 1985-1990",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Other Loss 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Vegetation Successional Growth 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Stable 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Non-Processing Area Mask 1985-1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wind 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Hurricane 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Snow or Ice Transition 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Desiccation 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Inundation 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Prescribed Fire 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Wildfire 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Mechanical Land Transformation 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Tree Removal 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.02,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Defoliation 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
Southern Pine Beetle 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0
"Insect, Disease, or Drought Stress 2005-2010",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,5.82,0.00,0.00,0.0,0.0
Other Loss 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.02,0.00,0.0,0.0
Vegetation Successional Growth 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,2.02,0.0,0.0
Stable 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,92.1,0.0
Non-Processing Area Mask 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.0,0.0

In [10]:
# Inline: Sankey diagram of LCMS Land Cover transitions
sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    sankey=True,
    transition_periods=[[1985, 1990], [2000, 2005], [2018, 2023]],
    title='LCMS Land Cover Transitions',
    min_percentage=0.5,
)
sankey_fig.show()
print('Source-Target-Value table:')
display(sankey_df)
print('Transition matrix:')
display(matrix_df)

Source-Target-Value table:

,source,target,value,source_name,target_name,source_color,target_color,period
0,9,24,15.46,1985-1990 Grass/Forb/Herb,1985-1990 Grass/Forb/Herb,#e5e98a,#e5e98a,1985-1990 -> 1985-1990
1,11,26,8.04,1985-1990 Barren or Impervious,1985-1990 Barren or Impervious,#893f54,#893f54,1985-1990 -> 1985-1990
2,13,28,1.44,1985-1990 Water,1985-1990 Water,#00b6f0,#00b6f0,1985-1990 -> 1985-1990
3,0,15,60.41,1985-1990 Trees,1985-1990 Trees,#004e2b,#004e2b,1985-1990 -> 1985-1990
4,2,17,0.87,1985-1990 Shrubs & Trees Mix,1985-1990 Shrubs & Trees Mix,#61bb46,#61bb46,1985-1990 -> 1985-1990
5,3,18,5.11,1985-1990 Grass/Forb/Herb & Trees Mix,1985-1990 Grass/Forb/Herb & Trees Mix,#acbb67,#acbb67,1985-1990 -> 1985-1990
6,4,19,0.63,1985-1990 Barren & Trees Mix,1985-1990 Barren & Trees Mix,#8b8560,#8b8560,1985-1990 -> 1985-1990
7,6,21,2.61,1985-1990 Shrubs,1985-1990 Shrubs,#f89a1c,#f89a1c,1985-1990 -> 1985-1990
8,7,22,5.10,1985-1990 Grass/Forb/Herb & Shrubs Mix,1985-1990 Grass/Forb/Herb & Shrubs Mix,#8fa55f,#8fa55f,1985-1990 -> 1985-1990
9,24,39,13.36,2000-2005 Grass/Forb/Herb,2000-2005 Grass/Forb/Herb,#e5e98a,#e5e98a,2000-2005 -> 2000-2005
10,26,41,8.37,2000-2005 Barren or Impervious,2000-2005 Barren or Impervious,#893f54,#893f54,2000-2005 -> 2000-2005
11,28,43,1.45,2000-2005 Water,2000-2005 Water,#00b6f0,#00b6f0,2000-2005 -> 2000-2005
12,15,30,61.26,2000-2005 Trees,2000-2005 Trees,#004e2b,#004e2b,2000-2005 -> 2000-2005
13,17,32,0.89,2000-2005 Shrubs & Trees Mix,2000-2005 Shrubs & Trees Mix,#61bb46,#61bb46,2000-2005 -> 2000-2005
14,18,33,5.44,2000-2005 Grass/Forb/Herb & Trees Mix,2000-2005 Grass/Forb/Herb & Trees Mix,#acbb67,#acbb67,2000-2005 -> 2000-2005
15,19,34,0.64,2000-2005 Barren & Trees Mix,2000-2005 Barren & Trees Mix,#8b8560,#8b8560,2000-2005 -> 2000-2005
16,21,36,1.95,2000-2005 Shrubs,2000-2005 Shrubs,#f89a1c,#f89a1c,2000-2005 -> 2000-2005
17,22,37,6.33,2000-2005 Grass/Forb/Herb & Shrubs Mix,2000-2005 Grass/Forb/Herb & Shrubs Mix,#8fa55f,#8fa55f,2000-2005 -> 2000-2005

Transition matrix:

,Trees 1985-1990,Tall Shrubs & Trees Mix (AK Only) 1985-1990,Shrubs & Trees Mix 1985-1990,Grass/Forb/Herb & Trees Mix 1985-1990,Barren & Trees Mix 1985-1990,Tall Shrubs (AK Only) 1985-1990,Shrubs 1985-1990,Grass/Forb/Herb & Shrubs Mix 1985-1990,Barren & Shrubs Mix 1985-1990,Grass/Forb/Herb 1985-1990,...,Tall Shrubs (AK Only) 2000-2005,Shrubs 2000-2005,Grass/Forb/Herb & Shrubs Mix 2000-2005,Barren & Shrubs Mix 2000-2005,Grass/Forb/Herb 2000-2005,Barren & Grass/Forb/Herb Mix 2000-2005,Barren or Impervious 2000-2005,Snow or Ice 2000-2005,Water 2000-2005,Non-Processing Area Mask 2000-2005
Trees 1985-1990,60.41,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tall Shrubs & Trees Mix (AK Only) 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shrubs & Trees Mix 1985-1990,0.00,0.0,0.87,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Grass/Forb/Herb & Trees Mix 1985-1990,0.00,0.0,0.00,5.11,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barren & Trees Mix 1985-1990,0.00,0.0,0.00,0.00,0.63,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tall Shrubs (AK Only) 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Shrubs 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,2.61,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Grass/Forb/Herb & Shrubs Mix 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,5.1,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barren & Shrubs Mix 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.24,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Grass/Forb/Herb 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,15.46,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barren & Grass/Forb/Herb Mix 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Barren or Impervious 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Snow or Ice 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Water 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Non-Processing Area Mask 1985-1990,0.00,0.0,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Trees 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Tall Shrubs & Trees Mix (AK Only) 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Shrubs & Trees Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Grass/Forb/Herb & Trees Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Barren & Trees Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Tall Shrubs (AK Only) 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Shrubs 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,1.95,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Grass/Forb/Herb & Shrubs Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,6.33,0.00,0.00,0.00,0.00,0.00,0.00,0.0
Barren & Shrubs Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.27,0.00,0.00,0.00,0.00,0.00,0.0
Grass/Forb/Herb 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,13.36,0.00,0.00,0.00,0.00,0.0
Barren & Grass/Forb/Herb Mix 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.0
Barren or Impervious 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,8.37,0.00,0.00,0.0
Snow or Ice 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.0
Water 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.45,0.0
Non-Processing Area Mask 2000-2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0

In [11]:
# Inline: Sankey diagram of LCMS Land Use transitions
sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
    lcms.select(['Land_Use']),
    study_area,
    sankey=True,
    transition_periods=[[1985, 1990], [2005, 2010], [2018, 2023]],
    title='LCMS Land Use Transitions',
    min_percentage=0.5,
)
sankey_fig.show()
print('Source-Target-Value table:')
display(sankey_df)
print('Transition matrix:')
display(matrix_df)

Source-Target-Value table:

,source,target,value,source_name,target_name,source_color,target_color,period
0,0,6,6.17,1985-1990 Agriculture,1985-1990 Agriculture,#fbff97,#fbff97,1985-1990 -> 1985-1990
1,1,7,7.14,1985-1990 Developed,1985-1990 Developed,#e6558b,#e6558b,1985-1990 -> 1985-1990
2,2,8,61.88,1985-1990 Forest,1985-1990 Forest,#004e2b,#004e2b,1985-1990 -> 1985-1990
3,3,9,5.92,1985-1990 Other,1985-1990 Other,#9dbac5,#9dbac5,1985-1990 -> 1985-1990
4,4,10,18.86,1985-1990 Rangeland or Pasture,1985-1990 Rangeland or Pasture,#a6976a,#a6976a,1985-1990 -> 1985-1990
5,6,12,4.60,2005-2010 Agriculture,2005-2010 Agriculture,#fbff97,#fbff97,2005-2010 -> 2005-2010
6,7,13,9.86,2005-2010 Developed,2005-2010 Developed,#e6558b,#e6558b,2005-2010 -> 2005-2010
7,8,14,62.05,2005-2010 Forest,2005-2010 Forest,#004e2b,#004e2b,2005-2010 -> 2005-2010
8,9,15,5.30,2005-2010 Other,2005-2010 Other,#9dbac5,#9dbac5,2005-2010 -> 2005-2010
9,10,16,18.19,2005-2010 Rangeland or Pasture,2005-2010 Rangeland or Pasture,#a6976a,#a6976a,2005-2010 -> 2005-2010

Transition matrix:

,Agriculture 1985-1990,Developed 1985-1990,Forest 1985-1990,Other 1985-1990,Rangeland or Pasture 1985-1990,Non-Processing Area Mask 1985-1990,Agriculture 2005-2010,Developed 2005-2010,Forest 2005-2010,Other 2005-2010,Rangeland or Pasture 2005-2010,Non-Processing Area Mask 2005-2010
Agriculture 1985-1990,6.17,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
Developed 1985-1990,0.00,7.14,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
Forest 1985-1990,0.00,0.00,61.88,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
Other 1985-1990,0.00,0.00,0.00,5.92,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN
Rangeland or Pasture 1985-1990,0.00,0.00,0.00,0.00,18.86,0.00,NaN,NaN,NaN,NaN,NaN,NaN
Non-Processing Area Mask 1985-1990,0.00,0.00,0.00,0.00,0.00,0.03,NaN,NaN,NaN,NaN,NaN,NaN
Agriculture 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,4.6,0.00,0.00,0.0,0.00,0.0
Developed 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.86,0.00,0.0,0.00,0.0
Forest 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,62.05,0.0,0.00,0.0
Other 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,5.3,0.00,0.0
Rangeland or Pasture 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,18.19,0.0
Non-Processing Area Mask 2005-2010,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.00,0.00,0.0,0.00,0.0

---
*  Adding a layer to line and sankey charting is done as follows

* Any time you specify `'line':True,'sankey':True`, both line and sankey charts will be created 

* This can slow things down a lot if many layers are visible. Also, moving the map, pausing for a second or two, and then moving the map again, many times, can create a long queue and delay charting.

In [ ]:
# Map-based approach: both line and sankey
Map.clearMap()

Map.addLayer(lcms.select(['Change']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'line':True,'sankey':True}},'LCMS Change')

Map.addLayer(lcms.select(['Land_Cover']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'line':True,'sankey':True}},'LCMS Land Cover')

Map.addLayer(lcms.select(['Land_Use']),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'line':True,'sankey':True}},'LCMS Land Use')


Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent — both line and sankey

* With `chartingLib`, you simply make two separate calls — one for the time series and one for the sankey

In [ ]:
# Inline: both time series and sankey for LCMS Land Cover

# Time series
df, fig = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    title='LCMS Land Cover (time series)',
    stacked=True,
)
fig.show()

# Sankey
sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    sankey=True,
    transition_periods=[[1985, 1990], [2005, 2010], [2018, 2023]],
    title='LCMS Land Cover (sankey)',
    min_percentage=0.5,
)
sankey_fig.show()
print('Transition matrix:')
display(matrix_df)

---
## Ways of adding area charting layers
* There are two methods for adding area chart layers. The first is shown above, where when adding a layer using `Map.addLayer`, specify `"canAreaChart":True`. With this method, if a layer is visible, it will be included in area charting.
* There are instances where you would like to summarize layers, but may not want them on the map or it is impossible to visualize all the thematic bands you'd like to chart. In this instance, you can use the `Map.addAreaChartLayer` method.
* If you use the `Map.addAreaChartLayer` method, you will need to use the `Map.populateAreaChartLayerSelect()` method to instantiate a selection menu for choosing which area chart layers should be charted. 
* In this example, we will summarize all thematic classes in LCMS in a single graph. This cannot be displayed on a map, but is an interesting way to look at the summarized data in charts

* Note that the dictionary of parameters is more or less the same as what you would put in the `"areaChartParams"` if you were to use the `Map.addLayer` method. 

* Note that while multi thematic band image collections can be charted in a single line chart, sankey charts can only support one band per chart. If a multi thematic band image collection is given with `"sankey":True` (as is the case in this example), separate sankey charts will be created for each band.

In [ ]:
# Map-based approach
Map.clearMap()

Map.addLayer(lcms.select(['Change_Raw_Probability.*']),{'reducer':ee.Reducer.stdDev(),'min':0,'max':10},'LCMS Change Prob')

Map.addAreaChartLayer(lcms,{'line':True},'LCMS All Thematic Classes Line',False)

Map.addAreaChartLayer(lcms,{'sankey':True},'LCMS All Thematic Classes Sankey',True)

Map.populateAreaChartLayerSelect()
Map.turnOnAutoAreaCharting()

Map.view()

### Inline chartingLib equivalent

* `chartingLib` can chart all thematic bands at once — just select multiple bands
* Column names are automatically prefixed with the band name when multiple bands are present

In [ ]:
# Inline: All LCMS thematic bands in one chart
df, fig = cl.summarize_and_chart(
    lcms.select(['Change', 'Land_Cover', 'Land_Use']),
    study_area,
    title='LCMS All Thematic Classes',
    stacked=True,
    width=800,
    height=500,
)
fig.show()
display(df.head())

---
## Charting Non-Thematic Data

* You can chart continuous data as well. By default, a `ee.Reducer.mean()` will be used. You can use any reducer that returns a single value per image-band (e.g. `ee.Reducer.min()`, `ee.Reducer.max()`, `ee.Reducer.stdDev()`, `ee.Reducer.mode()`, and not `ee.Reducer.percentile([0,50,100])`). 

* You can specify this using `"areaChartParams":{"reducer":ee.Reducer.mean()}`

* Optionally, you can provide a color palette to be used. Each band will be assigned to a color in the order given

* Notice in the example, the reducer for what is shown on the map is different from the zonal summary reducer. In this example, on the map the standard deviation of the probability is shown to highlight likely change, while the average over the area is shown in the chart since that is a more appropriate representation of probability over an area.

In [ ]:
# Map-based approach
Map.clearMap()

Map.addLayer(lcms.select(['Change_Raw_Probability.*']),
             {'reducer':ee.Reducer.stdDev(),'min':0,'max':10,'canAreaChart':True,'areaChartParams':{'palette':'f39268,d54309,00a398'}},'LCMS Change Prob')


Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

* `chartingLib` auto-detects continuous data (no class properties) and defaults to `ee.Reducer.mean()`
* For non-thematic data, `stacked=False` gives a multi-line chart

In [ ]:
# Inline: Continuous data — LCMS change probability bands
df, fig = cl.summarize_and_chart(
    lcms.select(['Change_Raw_Probability_Slow_Loss',
                 'Change_Raw_Probability_Fast_Loss',
                 'Change_Raw_Probability_Gain']),
    study_area,
    title='LCMS Change Probabilities (Mean)',
    stacked=False,
    palette=['f39268', 'd54309', '00a398'],
)
fig.show()
display(df)

---
## Charting Images

* You can also chart images
* It will behave in a similar fashion to imageCollections, but will show a bar chart
* Placing names for bar charts can be challenging if the names are very long. geeViz will automatically change the bar chart to be a horizontal bar chart if long names are detected. This still does not ensure the bar charts are readable (as is the case in this example). Shortening class names is the easiest method to address this issue (shown by splitting the full NLCD landcover name with `:` and take the first part earlier in this notebook).
* If using `"autoViz":True`, be sure to copy the `_class_` properties back in

In [ ]:
# Map-based approach
Map.clearMap()


Map.addLayer(lcms.select(['Land_Cover']),{'autoViz':True,'canAreaChart':True},'LCMS Land Cover')
Map.addLayer(lcms.select(['Land_Cover']).mode().set(lcms.first().toDictionary()),{'autoViz':True,'canAreaChart':True},'LCMS Land Cover Mode')

Map.addLayer(nlcd.select(['landcover']),{'autoViz':True,'canAreaChart':True},'NLCD Land Cover')
Map.addLayer(nlcd.select(['landcover']).mode().set(nlcd.first().toDictionary()),{'autoViz':True,'canAreaChart':True},'NLCD Land Cover Mode')

# Use the shortened class names to clean up chart
Map.addLayer(nlcd.select(['landcover']).mode().set(nlcd_props_shortened_names),{'autoViz':True,'canAreaChart':True},'NLCD Land Cover Mode Shortened Names')





Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

* For a single `ee.Image`, `chartingLib` produces a bar chart
* It auto-detects horizontal vs vertical orientation based on label length

In [ ]:
# Inline: Bar chart for LCMS Land Cover mode image
lc_mode = lcms.select(['Land_Cover']).mode().set(lcms.first().toDictionary())
df, fig = cl.summarize_and_chart(
    lc_mode,
    study_area,
    title='LCMS Land Cover Mode',
)
fig.show()
display(df)

In [ ]:
# Inline: Bar chart for NLCD landcover mode with original (long) names
# Notice how the long class names make the chart hard to read — compare with the shortened version below
nlcd_mode_long = nlcd.select(['landcover']).mode().set(nlcd.first().toDictionary())
df, fig = cl.summarize_and_chart(
    nlcd_mode_long,
    study_area,
    title='NLCD Land Cover Mode (Original Names)',
)
fig.show()
display(df)

In [ ]:
# Inline: Bar chart for NLCD landcover mode with shortened names
nlcd_mode = nlcd.select(['landcover']).mode().set(nlcd_props_shortened_names)
df, fig = cl.summarize_and_chart(
    nlcd_mode,
    study_area,
    title='NLCD Land Cover Mode (Shortened Names)',
)
fig.show()
display(df)

---
## Charting Images Without Color and Name Properties

* Sometimes you will have an image you add to the map with a min, max, and palette in the viz params that are thematic  or ordinal thematic data. If those images have no class_names, etc properties set, geeViz will try to render the chart properly using the given min, max, and palette if you specify `"areaChartParams":{"reducer":ee.Reducer.frequencyHistogram()}`

In [ ]:
# Map-based approach
Map.clearMap()

def getMostRecentChange(c, code):
    def wrapper(img):
        yr = ee.Date(img.get("system:time_start")).get("year")
        return (
            ee.Image(yr)
            .int16()
            .rename(["year"])
            .updateMask(img.eq(code))
            .copyProperties(img, ["system:time_start"])
        )

    return c.map(wrapper)

mostRecentFastLossYear = getMostRecentChange(lcms.select(['Change']),3).max()

Map.addLayer(mostRecentFastLossYear, {'min':1985,'max':2023,'palette':["ffffe5", "fff7bc", "fee391", "fec44f", "fe9929", "ec7014", "cc4c02"],'canAreaChart':True,'areaChartParams':{'reducer':ee.Reducer.frequencyHistogram()}}, "Most Recent Fast Loss Year", True)

Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

* Pass `reducer=ee.Reducer.frequencyHistogram()` to force thematic treatment
* Without class properties, class values are used as labels

In [ ]:
# Inline: Force frequencyHistogram for a non-class image
df, fig = cl.summarize_and_chart(
    mostRecentFastLossYear,
    study_area,
    reducer=ee.Reducer.frequencyHistogram(),
    title='Most Recent Fast Loss Year',
    palette=["ffffe5", "fff7bc", "fee391", "fec44f", "fe9929", "ec7014", "cc4c02"],
)
fig.show()
display(df)

---
## Charting Time Lapses 

* Time lapses also support area charting. All functionality is the same as the `Map.addLayer` methods.

* Band names can be specified in the `areaChartParams`. If they are not specified, but `bands` is specified in the visualization parameters, those bands will be used instead. Otherwise, all bands will be shown.

In [ ]:
# Map-based approach
Map.clearMap()

composites = ee.ImageCollection("projects/lcms-tcc-shared/assets/CONUS/Composites/Composite-Collection-yesL7")

years = list(range(1985,2024))

# Need to mosaic the tiled outputs for each year
composites = [composites.filter(ee.Filter.calendarRange(yr,yr,'year')).mosaic().set('system:time_start',ee.Date.fromYMD(yr,6,1).millis()) for yr in years]
composites = ee.ImageCollection(composites)

# Set up visualization parameters
viz = gil.vizParamsFalse10k
viz['canAreaChart']=True
viz['areaChartParams']={'bandNames':'blue,green,red,nir,swir1,swir2','palette':'00D,0D0,D00,D0D,0DD'}
Map.addTimeLapse(composites,gil.vizParamsFalse10k,'Composites')

Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

* Use `band_names` to select specific bands for a continuous time series
* `stacked=False` gives individual lines per band

In [ ]:
# Inline: Composite time series of spectral bands
df, fig = cl.summarize_and_chart(
    composites,
    study_area,
    band_names=['blue', 'green', 'red', 'nir', 'swir1', 'swir2'],
    title='Composite Band Means Over Time',
    stacked=False,
    palette=['00D', '0D0', 'D00', 'D0D', '0DD', 'DD0'],
)
fig.show()
display(df.head())

---
## Charting Thematic Data without set properties

* You can chart thematic datasets that lack values, names, and palette properties by specifying the `ee.Reducer.frequencyHistogram()` as the reducer

* This is not the best method however. Charts will lack descriptive class names and colors

In [ ]:
# Map-based approach: LCMAP example
Map.clearMap()


lcpri = ee.ImageCollection("projects/sat-io/open-datasets/LCMAP/LCPRI").select(['b1'],['LC'])


Map.addTimeLapse(lcpri,{'min':1,'max':9,'canAreaChart':True,"areaChartParams":{'reducer':ee.Reducer.frequencyHistogram()}},'LCMAP LC Primary')

Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

In [ ]:
# Inline: LCMAP without class properties — just uses class values as labels
df, fig = cl.summarize_and_chart(
    lcpri.filterBounds(study_area),
    study_area,
    reducer=ee.Reducer.frequencyHistogram(),
    title='LCMAP LC Primary (no class properties)',
    stacked=True,
)
fig.show()
display(df.head())

---
### Setting properties for charting

* The easiest way to chart thematic data where each class has a number, name, and color, but lack the preset properties, is to set them on-the-fly

* These properties can then be used for charting and map rendering

In [ ]:
# Map-based approach: LCMAP with manually set properties
Map.clearMap()

lcpri_palette = ['E60000','A87000','E3E3C2','1D6330','476BA1','BAD9EB','FFFFFF','B3B0A3','A201FF']
lc_names = ['Developed','Cropland','Grass/Shrub','Tree Cover','Water','Wetlands','Ice/Snow','Barren','Class Change']
lc_numbers = list(range(1,len(lcpri_palette)+1))

lcpri = ee.ImageCollection("projects/sat-io/open-datasets/LCMAP/LCPRI").select(['b1'],['LC'])

lcpri = lcpri.map(lambda img:img.set({'LC_class_values':lc_numbers,'LC_class_names':lc_names,'LC_class_palette':lcpri_palette}))


Map.addTimeLapse(lcpri,{'autoViz':True,'canAreaChart':True,'areaChartParams':{'line':True,'sankey':True}},'LCMAP LC Primary')

Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

In [ ]:
# Inline: LCMAP with class properties — time series
df, fig = cl.summarize_and_chart(
    lcpri,
    study_area,
    title='LCMAP LC Primary',
    stacked=True,
)
fig.show()
display(df.head())

In [ ]:
# Inline: LCMAP sankey
sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
    lcpri,
    study_area,
    sankey=True,
    transition_periods=[[1985, 1990], [2000, 2005], [2018, 2021]],
    title='LCMAP LC Primary Transitions',
    min_percentage=0.5,
)
sankey_fig.show()
print('Source-Target-Value table:')
display(sankey_df)
print('Transition matrix:')
display(matrix_df)

---
## Comparing map output versions

* One common task is to understand the differences between 2 or more model runs. This can be challenging.

* This example will show three versions of LCMS products and how they relate

* This approach makes comparing the maps and their respective class counts relatively easy

* This idea could be adapted to comparing different thematic or continuous outputs

In [ ]:
# Map-based approach
Map.clearMap()

# Bring in 3 different LCMS versions
lcms_2020 = ee.ImageCollection("USFS/GTAC/LCMS/v2020-5").filter('study_area=="CONUS"')
lcms_2021 = ee.ImageCollection("USFS/GTAC/LCMS/v2021-7").filter('study_area=="CONUS"')
lcms_2022 = ee.ImageCollection("USFS/GTAC/LCMS/v2022-8").filter('study_area=="CONUS"')
lcms_2023 = ee.ImageCollection("USFS/GTAC/LCMS/v2023-9").filter('study_area=="CONUS"')

# Choose a year to compare (any year 1985-2020)
year = 2010

# Filter off the image and set that image to the version year
lcms_2020 = lcms_2020.filter(ee.Filter.calendarRange(year,year,'year')).first().set({'year':2020,'system:time_start':ee.Date.fromYMD(2020,6,1).millis()})
lcms_2021 = lcms_2021.filter(ee.Filter.calendarRange(year,year,'year')).first().set({'year':2021,'system:time_start':ee.Date.fromYMD(2021,6,1).millis()})
lcms_2022 = lcms_2022.filter(ee.Filter.calendarRange(year,year,'year')).first().set({'year':2022,'system:time_start':ee.Date.fromYMD(2022,6,1).millis()})
lcms_2023 = lcms_2023.filter(ee.Filter.calendarRange(year,year,'year')).first().set({'year':2023,'system:time_start':ee.Date.fromYMD(2023,6,1).millis()})

# Construct the image collection
c = ee.ImageCollection([lcms_2020,lcms_2021,lcms_2022,lcms_2023])

# Add the collection as a timelapse
# Will need to specify the transition years as the years used for each image, otherwise geeViz will default to only showing the first and last year
# Note that if you specify the sankey transition periods, any periods you enter in the geeViz UI will not be used for that layer
for bn in ['Change','Land_Cover','Land_Use']:
  Map.addTimeLapse(c.select([bn]),{'autoViz':True,'canAreaChart':True,'areaChartParams':{'sankey':True,
                                                                            'sankeyTransitionPeriods':[[2020,2020],[2021,2021],[2022,2022],[2023,2023]]
                                                                            }}, f"LCMS {bn.replace('_',' ')} Comparison {year}")

Map.turnOnAutoAreaCharting()
Map.view()

### Inline chartingLib equivalent

In [ ]:
# Inline: Version comparison — time series + sankey
for bn in ['Change', 'Land_Cover', 'Land_Use']:
    # Time series
    df, fig = cl.summarize_and_chart(
        c.select([bn]),
        study_area,
        title=f'LCMS {bn.replace("_", " ")} Comparison {year}',
        stacked=True,
    )
    fig.show()

    # Sankey
    sankey_df, sankey_fig, matrix_df = cl.summarize_and_chart(
        c.select([bn]),
        study_area,
        sankey=True,
        transition_periods=[[2020, 2020], [2021, 2021], [2022, 2022], [2023, 2023]],
        title=f'LCMS {bn.replace("_", " ")} Version Transitions {year}',
        min_percentage=0.5,
    )
    sankey_fig.show()
    print(f'Transition matrix for {bn}:')
    display(matrix_df)

---
## Other charting summary zone selection methods

* All examples have simply used the map extent as the zone to chart

* There are other methods available

* This example will show how to add a featureCollection to interactively select areas to summarize

* All area selection will happen in the geeViz UI, under `Tools -> Area Tools -> Select an Area on Map`

* This example also demonstrates the use of the stacked bar `chartType` and turning off the first and last MTBS burn severity classes in the chart

In [ ]:
# Map-based approach
Map.clearMap()


for bn in ['Change','Land_Cover','Land_Use']:
  Map.addLayer(lcms.select([bn]),{'autoViz':True,'canAreaChart':True}, f"LCMS {bn.replace('_',' ')}  ")


# Bring in MTBS burn boundaries
mtbsBoundaries = ee.FeatureCollection("USFS/GTAC/MTBS/burned_area_boundaries/v1")
mtbsBoundaries = mtbsBoundaries.map(
    lambda f: f.set("system:time_start", f.get("Ig_Date"))
)
# Bring in MTBS burn severity mosaics
mtbsSeverity = ee.ImageCollection("USFS/GTAC/MTBS/annual_burn_severity_mosaics/v1").filter(ee.Filter.stringContains('system:index','_CONUS_'))
Map.addLayer(mtbsSeverity,{'autoViz':True,'canAreaChart':True,'areaChartParams':{'chartType':'stacked-bar',"visible": [False, True, True, True, True, True, False],}}, "MTBS Burn Severity")

# For area charting you can select areas to chart a number of ways. One method is using a map layer that is selectable by clicking on each feature.
Map.addSelectLayer(
    mtbsBoundaries,
    {
        "strokeColor": "00F",
        "selectLayerNameProperty": "Incid_Name",
    },
    "MTBS Fire Boundaries"
)

Map.turnOnSelectionAreaCharting()
Map.view()

### Inline chartingLib equivalent

* With `chartingLib` you can pass any `ee.FeatureCollection` as the geometry
* For a single-feature FC (e.g. a state boundary), it behaves like a single geometry
* This is useful for scripted, reproducible analyses where you want to specify the exact zone
* Below we chart all LCMS thematic bands and MTBS Burn Severity over Colorado

In [ ]:
# Inline: LCMS thematic bands summarized over Colorado
co = ee.FeatureCollection('TIGER/2018/States').filter(ee.Filter.eq('NAME', 'Colorado'))

for bn in ['Change', 'Land_Cover', 'Land_Use']:
    df, fig = cl.summarize_and_chart(
        lcms.select([bn]),
        co,
        title=f'LCMS {bn.replace("_", " ")} \u2014 Colorado',
        stacked=True,
    )
    fig.show()

In [ ]:
# Inline: MTBS Burn Severity stacked bar chart over Colorado
mtbsSeverity = ee.ImageCollection("USFS/GTAC/MTBS/annual_burn_severity_mosaics/v1").filter(ee.Filter.stringContains('system:index', '_CONUS_'))

df, fig = cl.summarize_and_chart(
    mtbsSeverity,
    co,
    title='MTBS Burn Severity \u2014 Colorado',
    chart_type='bar',
    stacked=True,
)
fig.show()
display(df.head())

---
## Multi-Feature `reduceRegions` (chartingLib only)

* When you pass a multi-feature `ee.FeatureCollection` as the geometry **and** set `feature_label` to the name of a feature property, `chartingLib` uses `reduceRegions` to compute per-feature statistics in a single server call
* The result is a grouped bar chart where each group is a feature (fire, state, watershed, etc.) and each bar within the group is a class
* This is far more efficient than looping over features individually

* In this example we find the 5 largest MTBS fires and summarize both LCMS Land Cover and Annual NLCD over each fire perimeter

In [ ]:
# Get the 5 largest MTBS fire perimeters by burned area (BurnBndAc)
mtbs_perims = ee.FeatureCollection("USFS/GTAC/MTBS/burned_area_boundaries/v1")
top5_fires = mtbs_perims.sort("BurnBndAc", False).limit(5)

# Shorten fire names for readability
top5_fires = top5_fires.map(lambda f: f.set("Fire", ee.String(f.get("Incid_Name")).cat(' (').cat(ee.Number(f.get("Ig_Year")).format("%d")).cat(")")))

print("5 largest MTBS fires:")
for feat in top5_fires.getInfo()["features"]:
    p = feat["properties"]
    print(f"  {p.get("Fire", p.get("Incid_Name"))}: {p["BurnBndAc"]:,.0f} acres")

In [ ]:
# LCMS Land Cover mode over the 5 largest fires (reduceRegions)
lc_mode = lcms.select(["Land_Cover"]).mode().set(lcms.first().toDictionary())

df, fig = cl.summarize_and_chart(
    lc_mode,
    top5_fires,
    feature_label="Fire",
    title="LCMS Land Cover Mode — 5 Largest MTBS Fires",
    stacked=True,
    width=800,
    height=450,
)
fig.show()
display(df)

In [ ]:
# Annual NLCD landcover mode over the 5 largest fires (reduceRegions)
nlcd_mode_fires = nlcd.select(["landcover"]).mode().set(nlcd_props_shortened_names)

df, fig = cl.summarize_and_chart(
    nlcd_mode_fires,
    top5_fires,
    feature_label="Fire",
    title="NLCD Land Cover Mode — 5 Largest MTBS Fires",
    stacked=True,
    width=800,
    height=450,
)
fig.show()
display(df)

---
## Area Format Options (chartingLib only)

* By default, thematic charts show percentages
* You can switch to hectares, acres, or raw pixel counts using the `area_format` parameter

In [ ]:
# Inline: Same data in hectares
df_ha, fig_ha = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    area_format='Hectares',
    title='LCMS Land Cover (Hectares)'
)
fig_ha.show()

# And in acres
df_ac, fig_ac = cl.summarize_and_chart(
    lcms.select(['Land_Cover']),
    study_area,
    area_format='Acres',
    title='LCMS Land Cover (Acres)'
)
fig_ac.show()

---
## Using the Lower-Level Functions (chartingLib only)

* `summarize_and_chart` is a convenience wrapper
* You can also call the lower-level functions directly for more control:
  - `cl.get_obj_info()` \u2014 inspect the object type and class metadata
  - `cl.zonal_stats()` \u2014 get just the DataFrame (no chart)
  - `cl.chart_time_series()` / `cl.chart_bar()` / `cl.chart_sankey()` \u2014 build charts from DataFrames

In [ ]:
# Step-by-step: inspect, compute stats, then chart
lc = lcms.select(['Land_Cover'])

# 1. Inspect the object
info = cl.get_obj_info(lc)
print('Object info:')
for k, v in info.items():
    if k != 'class_info':
        print(f'  {k}: {v}')
print(f'  class_info bands: {list(info["class_info"].keys())}')

# 2. Compute zonal stats (returns just the DataFrame)
df = cl.zonal_stats(lc, study_area, area_format='Percentage')
print(f'\nDataFrame shape: {df.shape}')
display(df.head())

# 3. Build chart from the DataFrame
colors = info['class_info']['Land_Cover']['class_palette']
fig = cl.chart_time_series(
    df,
    colors=colors,
    title='LCMS Land Cover (step-by-step)',
    y_label='% Area'
)
fig.show()